# Generated by Django 5.1.4 on 2025-01-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spamreport',
            name='marked_by',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='SpamReport',
        ),
    ]
